# **1. Import Library**

Pada tahap ini, Anda perlu mengimpor beberapa pustaka (library) Python yang dibutuhkan untuk analisis data dan pembangunan model machine learning.

In [22]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [23]:
#Type your code here
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, recall_score, f1_score, precision_score

# **2. Memuat Dataset dari Hasil Clustering**

Memuat dataset hasil clustering dari file CSV ke dalam variabel DataFrame.

In [24]:
#Type your code here
df = pd.read_csv('/content/drive/MyDrive/Dicoding_DataScience/Submission_ML/Clustered.csv')
df

,Education,Marital_Status,Income,Recency,Wine,Fruit,Meat,Fish,Sweet,Gold,Age,Spent,Living_With,Children,Total_Purchases,Total_Campaign,Cluster
0,2,4,58138.0,58,635,88,546,172,88,88,67,1071,0,0,25,0,2
1,2,4,46344.0,38,11,1,6,2,1,6,70,21,0,2,6,0,0
2,2,5,71613.0,26,426,49,127,111,21,42,59,649,1,0,21,0,3
3,2,5,26646.0,26,11,4,20,10,3,5,40,33,1,1,8,0,1
4,4,3,58293.0,94,173,43,118,46,27,15,43,304,1,1,19,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2231,2,3,61223.0,46,709,43,182,42,118,247,57,1159,1,1,18,0,3
2232,4,5,64014.0,56,406,0,30,0,0,8,78,414,1,3,22,1,1
2233,2,2,56981.0,91,908,48,217,32,12,24,43,1024,0,0,19,1,2
2234,3,5,69245.0,8,428,30,214,80,30,61,68,629,1,1,23,0,3
2235,4,3,52869.0,40,84,3,61,2,1,21,70,111,1,2,11,0,1

# **3. Data Splitting**

Tahap Data Splitting bertujuan untuk memisahkan dataset menjadi dua bagian: data latih (training set) dan data uji (test set).

In [25]:
#Type your code here
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2236 entries, 0 to 2235
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Education        2236 non-null   int64
 1   Marital_Status   2236 non-null   int64
 2   Income           2236 non-null   float64
 3   Recency          2236 non-null   int64
 4   Wine             2236 non-null   int64
 5   Fruit            2236 non-null   int64
 6   Meat             2236 non-null   int64
 7   Fish             2236 non-null   int64
 8   Sweet            2236 non-null   int64
 9   Gold             2236 non-null   int64
 10  Age              2236 non-null   int64
 11  Spent            2236 non-null   int64
 12  Living_With      2236 non-null   int64
 13  Children         2236 non-null   int64
 14  Total_Purchases  2236 non-null   int64
 15  Total_Campaign   2236 non-null   int64
 16  Cluster          2236 non-null   int64
dtypes: float64(1), int64(16)
memory usage: 297.1 KB

In [26]:
df.isnull().sum()

Education          0
Marital_Status     0
Income             0
Recency            0
Wine               0
Fruit              0
Meat               0
Fish               0
Sweet              0
Gold               0
Age                0
Spent              0
Living_With        0
Children           0
Total_Purchases    0
Total_Campaign     0
Cluster            0
dtype: int64

### Pembagian Data

In [27]:
X = df.drop(columns=['Cluster'])
y = df['Cluster']
print(X, y)

      Education  Marital_Status   Income  Recency  Wine  Fruit  Meat  Fish  \
0             2               4  58138.0       58   635     88   546   172
1             2               4  46344.0       38    11      1     6     2
2             2               5  71613.0       26   426     49   127   111
3             2               5  26646.0       26    11      4    20    10
4             4               3  58293.0       94   173     43   118    46
...         ...             ...      ...      ...   ...    ...   ...   ...
2231          2               3  61223.0       46   709     43   182    42
2232          4               5  64014.0       56   406      0    30     0
2233          2               2  56981.0       91   908     48   217    32
2234          3               5  69245.0        8   428     30   214    80
2235          4               3  52869.0       40    84      3    61     2

      Sweet  Gold  Age  Spent  Living_With  Children  Total_Purchases  \
0        88    88   67   1071            0         0               25
1         1     6   70     21            0         2                6
2        21    42   59    649            1         0               21
3         3     5   40     33            1         1                8
4        27    15   43    304            1         1               19
...     ...   ...  ...    ...          ...       ...              ...
2231    118   247   57   1159            1         1               18
2232      0     8   78    414            1         3               22
2233     12    24   43   1024            0         0               19
2234     30    61   68    629            1         1               23
2235      1    21   70    111            1         2               11

      Total_Campaign
0                  0
1                  0
2                  0
3                  0
4                  0
...              ...
2231               0
2232               1
2233               1
2234               0
2235               0

[2236 rows x 16 columns] 0       2
1       0
2       3
3       1
4       1
       ..
2231    3
2232    1
2233    2
2234    3
2235    1
Name: Cluster, Length: 2236, dtype: int64

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)
print('Data X:')
print(X_train.shape, X_test.shape)
print('Data y:')
print(y_train.shape, y_test.shape)

Data X:
(1788, 16) (448, 16)
Data y:
(1788,) (448,)

# **4. Membangun Model Klasifikasi**

## **a. Membangun Model Klasifikasi**

Setelah memilih algoritma klasifikasi yang sesuai, langkah selanjutnya adalah melatih model menggunakan data latih.

Berikut adalah rekomendasi tahapannya.
1. Pilih algoritma klasifikasi yang sesuai, seperti Logistic Regression, Decision Tree, Random Forest, atau K-Nearest Neighbors (KNN).
2. Latih model menggunakan data latih.

In [29]:
#Type your code here
def DecisionTree(X, y):
  model = DecisionTreeClassifier()
  model.fit(X, y)
  return model

def KNN(X, y):
  model = KNeighborsClassifier()
  model.fit(X, y)
  return model

def RandomForest(X, y):
  model = RandomForestClassifier()
  model.fit(X, y)
  return model

Tulis narasi atau penjelasan algoritma yang Anda gunakan.

## **b. Evaluasi Model Klasifikasi**

Berikut adalah **rekomendasi** tahapannya.
1. Lakukan prediksi menggunakan data uji.
2. Hitung metrik evaluasi seperti Accuracy dan F1-Score (Opsional: Precision dan Recall).
3. Buat confusion matrix untuk melihat detail prediksi benar dan salah.

In [30]:
def evaluate_model(model, X_test, y_test):
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')
    cm = confusion_matrix(y_test, y_pred)

    evaluation_metrics = {
        'accuracy': accuracy,
        'precision': precision,
        'recall': recall,
        'f1_score': f1,
        'confusion_matrix': cm
    }

    print(classification_report(y_test, y_pred))

    return evaluation_metrics

### **1. Model KNN**

In [31]:
knn_metrics = evaluate_model(KNN(X_train, y_train), X_test, y_test)

              precision    recall  f1-score   support

           0       0.30      0.23      0.26        97
           1       0.60      0.72      0.66       174
           2       0.47      0.41      0.44        58
           3       0.74      0.71      0.72       119

    accuracy                           0.57       448
   macro avg       0.53      0.52      0.52       448
weighted avg       0.56      0.57      0.56       448

### **2. Model Decision Tree**

In [32]:
DT_metrics = evaluate_model(DecisionTree(X_train, y_train), X_test, y_test)

              precision    recall  f1-score   support

           0       0.96      0.98      0.97        97
           1       0.99      0.98      0.99       174
           2       0.96      0.93      0.95        58
           3       0.97      0.98      0.98       119

    accuracy                           0.98       448
   macro avg       0.97      0.97      0.97       448
weighted avg       0.98      0.98      0.98       448

### **3. Model Random Forest**

In [33]:
RF_metrics = evaluate_model(RandomForest(X_train, y_train), X_test, y_test)

              precision    recall  f1-score   support

           0       0.98      0.99      0.98        97
           1       0.99      0.99      0.99       174
           2       0.98      0.97      0.97        58
           3       0.98      0.98      0.98       119

    accuracy                           0.98       448
   macro avg       0.98      0.98      0.98       448
weighted avg       0.98      0.98      0.98       448

## **c. Tuning Model Klasifikasi (Optional)**

Gunakan GridSearchCV, RandomizedSearchCV, atau metode lainnya untuk mencari kombinasi hyperparameter terbaik

In [34]:
#Type your code here

## **d. Evaluasi Model Klasifikasi setelah Tuning (Optional)**

Berikut adalah rekomendasi tahapannya.
1. Gunakan model dengan hyperparameter terbaik.
2. Hitung ulang metrik evaluasi untuk melihat apakah ada peningkatan performa.

In [35]:
#Type your code here

## **e. Analisis Hasil Evaluasi Model Klasifikasi**

Berikut adalah **rekomendasi** tahapannya.
1. Bandingkan hasil evaluasi sebelum dan setelah tuning (jika dilakukan).
2. Identifikasi kelemahan model, seperti:
  - Precision atau Recall rendah untuk kelas tertentu.
  - Apakah model mengalami overfitting atau underfitting?
3. Berikan rekomendasi tindakan lanjutan, seperti mengumpulkan data tambahan atau mencoba algoritma lain jika hasil belum memuaskan.

In [36]:
results = []

# KNN
results.append(['KNN', knn_metrics['accuracy'], knn_metrics['precision'], knn_metrics['recall'], knn_metrics['f1_score']])

# Decision Tree
results.append(['Decision Tree', DT_metrics['accuracy'], DT_metrics['precision'], DT_metrics['recall'], DT_metrics['f1_score']])

# Random Forest
results.append(['Random Forest', RF_metrics['accuracy'], RF_metrics['precision'], RF_metrics['recall'], RF_metrics['f1_score']])

results_df = pd.DataFrame(results, columns=['Model', 'Accuracy', 'Precision', 'Recall', 'F1-Score'])
results_df

           Model  Accuracy  Precision    Recall  F1-Score
0            KNN  0.571429   0.555169  0.571429  0.559796
1  Decision Tree  0.975446   0.975497  0.975446  0.975405
2  Random Forest  0.984375   0.984381  0.984375  0.984363

### **Kesimpulan:**
1. Model dengan dataset customer segmentation dengan output klasifikasi 3 kelas ini dapat dieksekusi dengan sangat baik menggunakan Decision Tree dan Ranfom Forest. Hal tersebut terjadi karena random forest dan decision tree adalah model yang mampu mengklasifikasi walaupun hubungan antar atribut data tidak linier.
2. Model dengan kemampuan akurasi dan F1-Score terbaik ditunjukkan oleh Random Forest. Dengan akurasi dan f1-score sebesar 0,98 secara berturut - turut.
3. KNN menghasilkan evaluation metrics yang lebih rendah dibanding dua model Tree lainnya adalah karena KNN bekerja menggunakan perhitungan jarak sedangkan Tree menggunakan pembagian data berdasarkan fitur masing-masing sehingga non linearitas dapat dieksekusi dengan baik.